### ISSUE TITLE
Test SAML federation approach 1 in HA mode

### ISSUE THREAD

**Issue by NicolasLiampotis** [eosc-kc/keycloak#30]
We need to test SAML federation approach 1 in HA mode. It may be required to extend caching mechanism to properly support HA.

Last resort: Disable cache for entities only?

Test VMs:
1. cappakleis3.aai-dev.grnet.gr
2. cappakleis4.aai-dev.grnet.gr

**Comment by laskasn** [comment]
A fully functional deployment of a keycloak in high availability mode is setup on the 2 machines [cappakleis3.aai-dev.grnet.gr, cappakleis4.aai-dev.grnet.gr].
More specifically, the services installed on these machines are:

- cappakleis3 : Keycloak instance, postgresql database (shared)
- cappakleis3 : Keycloak instance, nginx load balancer and reverse proxy

**Comment by laskasn** [comment]
We inserted edugain federation in the cluster - it now has ~3200 idps. 
As a final step, we will check a couple of performance parameters - synchronisation delays, traffic exchange between nodes, etc, just to be sure that this works as expected.

**Comment by laskasn** [comment]
I noticed that there is a huge amount of data sent across the cache cluster whenever the federation with all the IdPs are populated. A refactoring on the code is needed to fix this, so, let's keep it under "In Progress" till i refactor and update the running instances.

**Comment by laskasn** [comment]
I managed to split the cache in smaller chunks, with the use of an additional infinispan query module. However, it seems that there is a classpath problem with wildfly's existing infinispan modules. I must re-design the cache, avoiding the query module.

**Comment by laskasn** [comment]
Refactored the infinispan caching for the Idps and their mappers. Used cluster-wide notifications for all changes, rather than distributed synchronized caches. Redeployed them on the cluster {cappakleis3 and cappakleis4}

**Comment by laskasn** [comment]
Works fine now - cluster tests are also ok. Maybe we could code an invalidation scheme for the node caches (as keycloak developers prefer) rather than the synchronized cluster scheme we currently use.

**Comment by laskasn** [comment]
This should be closed now
